[package]
name = "rational_deduction"
version = "0.0.0"
edition = "2018"
authors = ["Brandon H. Gomes <bh.gomes@rutgers.edu>"]
documentation = "https://docs.rs/rational_deduction"
homepage = "https://github.com/qdeduction/rational_deduction.rs"
repository = "https://github.com/qdeduction/rational_deduction.rs"
readme = "README.md"
license = "ISC"
keywords = ["deduction"]
categories = [""]
description = "Rust implementation of the rational deduction algorithm."
exclude = [""]
publish = false

[badges]
is-it-maintained-issue-resolution = { repository = "qdeduction/rational_deduction.rs" }
is-it-maintained-open-issues = { repository = "qdeduction/rational_deduction.rs" }
maintenance = { status = "actively-developed" }

[dependencies]
exprz-core = "0.0.1"

